sudo: false
language: node_js
node_js:
 - "node"

cache:
  directories:
  - node_modules

env:
  global:
    - epic_jwtPrivateKey=EPIC-mail
    - NODE_ENV=testing

script: "npm test && nyc report --reporter=text-lcov | coveralls"

