/* eslint-disable no-unused-vars */
const dummyData = {
  messages: [
    {
      id: 1,
      createdOn: 'Sat 18th, Mar 2011',
      subject: 'i just registered',
      receiverId: 2,
      senderId: 1,
      mailerName: 'paul jekande',
      message: 'its so wonderful to be part of this app',
      parentMessageId: undefined,
      status: 'unread',
    },
    {
      id: 3,
      createdOn: 'Sun 11th, Aug 2018',
      receiverId: 1,
      senderId: 2,
      mailerName: 'fred delight',
      subject: "get in the car, you're late",
      message: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
      parentMessageId: undefined,
      status: 'sent',
    },
    {
      id: 4,
      createdOn: 'Thu 23rd, Jan 2019',
      receiverId: 2,
      senderId: 1,
      mailerName: 'fred delight',
      subject: 'hello, missed your call',
      message: "I'm so sorry, i was at the inn when you called martins, Lorem Ipsum is simply dummy text",
      parentMessageId: undefined,
      status: 'read',
    },
    {
      id: 6,
      createdOn: 'Sat 23rd, Jun 2015',
      receiverId: 1,
      senderId: 2,
      mailerName: 'kunle sambo',
      subject: 'the staff meeting',
      message: 'dont let the board members get on your nerves they have terrible manners',
      parentMessageId: undefined,
      status: 'draft',
    },
  ],
  filtered: [],
};
